### ISSUE TITLE
Story schreiben 

### ISSUE THREAD

**Issue by SickMi** [Fuenfgeld/2022TeamADataEngineeringBC#16]
Clarkson’s Farm 
Wir fangen an Sachen ... anzupflanzen 
Was wird gebraucht... wir greifen auf unsere Daten zu und Formen sie um 

wir eröffnen mit unseren Produkten einen Hofladen ..
was brauchen wir

**Comment by niklasbuechner** [comment]
Die Story sieht gut aus 👍

**Comment by niklasbuechner** [comment]
Hier mal noch der Link dazu: https://github.com/Fuenfgeld/2022TeamADataEngineeringBC/wiki/Story
