### ISSUE TITLE
Git repository aufräumen

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/2022TeamADataEngineeringBC#59]
Es gibt zu viele datein die redundant scheinen. Uebungen , Tutorial. Ich würde das vielleicht zusammenführen in eine datei. Ich würde auch eure Abbildungen aus der präsentation in die Colab einbinden. Eure input daten (iris.csv) würde ich in einen extra folder legen

**Comment by niklasbuechner** [comment]
Todos:
- [x] Übungen & Tutorials zusammenführen @SickMi & @Github-DAF1 
- [x] iris.csv in einen Unterordner legen. @niklasbuechner
